sonar.projectKey=skiox-project

sonar.sourceEncoding=UTF-8

sonar.modules=api,ihm

api.sonar.projectName=Skiox API
api.sonar.projectBaseDir=Back/API
api.sonar.sources=src
api.sonar.tests=src
api.sonar.test.inclusions=**/*.spec.js,**/*.test.js
api.sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.spec.js,**/*.test.js
api.sonar.javascript.lcov.reportPaths=coverage/lcov.info

ihm.sonar.projectName=Skiox IHM
ihm.sonar.projectBaseDir=IHM
ihm.sonar.sources=src
ihm.sonar.tests=src
ihm.sonar.test.inclusions=**/*.spec.ts
ihm.sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,src/environments/**